"""Type stubs for the native _ifc_lite extension module."""

from typing import Any

def process_file(path: str) -> dict[str, Any]: ...
def process_text(content: str) -> dict[str, Any]: ...
def process_text_filtered(content: str, filter_mode: int) -> dict[str, Any]: ...
def version() -> str: ...
